import smtplib
from email.message import EmailMessage

import yaml
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts.chat import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from src.app.config import LLMModelSettings, MailSettings, Settings
from src.app.database.langchain_qdrant_wrapper import QdrantLangchainWrapper
from src.app.factory.openai_chat_model import init_openai_chat_model
from src.app.schemas.action import ActionProposal
from src.app.schemas.insight import Insight


def _run_retrival_insight_chain(insight: Insight, llm_model_settings: LLMModelSettings):
    chat_prompt = ChatPromptTemplate([
        ("system", llm_model_settings.prompts.propose_action_prompt),
        ("human", "Create the action proposal based on the given insight information.")
    ])

    llm_chat = init_openai_chat_model(llm_model_settings)
    parser = PydanticOutputParser(pydantic_object=ActionProposal)

    chain = chat_prompt | llm_chat | parser

    response = chain.invoke({
        "title": insight.title,
        "summary": insight.summary[:2000],
        "format_instruction": parser.get_format_instructions()
    })

    return response


def _propose_action(
        insight: Insight,
        llm_model_settings: LLMModelSettings,
):
    """

    :param insight:
    :param llm_model_settings:
    :return:
    """

    response = _run_retrival_insight_chain(
        insight=insight,
        llm_model_settings=llm_model_settings
    )

    return response


def create_action_proposal_on_given_insight(
        insight: Insight,
        settings: Settings,
):
    insight = insight

    action_proposal = _propose_action(
        insight=insight,
        llm_model_settings=settings.llm_model
    )

    return action_proposal


def send_mail(
        action: ActionProposal,
        email_settings: MailSettings
):
    msg = EmailMessage()
    msg["FROM"] = email_settings.smtp_from
    msg["TO"] = email_settings.smtp_to
    msg["subject"] = f"[INSIGHT_ACTION_AGENT]: {action.title}"
    pretty_payload = yaml.dump(action.payload, allow_unicode=True, sort_keys=False)
    msg.set_content(f"This is an autogenerated message form the Insight -> Action Agent! \n\n"
                    f"{action.description}\n"
                    f"Following payload for the Action is necessary to work on:\n"
                    f"{pretty_payload}")

    try:
        with smtplib.SMTP_SSL(email_settings.smtp_host, email_settings.smtp_port) as smtp:
            smtp.login(email_settings.smtp_username, email_settings.smtp_password)
            smtp.send_message(msg)
    except Exception as e:
        return {"status": "error", "message": str(e)}

    return {"status": "success", "message": "email sent"}
